openapi: 3.0.0
info:
  title: HSK API Minimal
  version: 1.0.0
  description: Минимальная версия API для HSK приложения

paths:
  /api/subscription/channels:
    get:
      summary: Получить список обязательных каналов
      parameters:
        - name: x-api-key
          in: header
          required: true
          schema:
            type: string
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ed7ivm48jur40il1m8
        service_account_id: ajevmvf8t8qda5d7lqlp
      responses:
        '200':
          description: OK
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
                default: "https://hsk-delta.vercel.app"
            Access-Control-Allow-Methods:
              schema:
                type: string
                default: "GET, POST, OPTIONS"
            Access-Control-Allow-Headers:
              schema:
                type: string
                default: "Content-Type, x-api-key"
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
    options:
      summary: CORS preflight
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ed7ivm48jur40il1m8
        service_account_id: ajevmvf8t8qda5d7lqlp
      responses:
        '200':
          description: OK
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
                default: "https://hsk-delta.vercel.app"
            Access-Control-Allow-Methods:
              schema:
                type: string
                default: "GET, POST, OPTIONS"
            Access-Control-Allow-Headers:
              schema:
                type: string
                default: "Content-Type, x-api-key"

  /health:
    get:
      summary: Health check
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ed7ivm48jur40il1m8
        service_account_id: ajevmvf8t8qda5d7lqlp
      responses:
        '200':
          description: OK