name: Deploy to Yandex Cloud Functions

on:
  push:
    branches: [ main, master ]
    paths: 
      - 'backend/**'
      - 'functions/**'
      - '.github/workflows/deploy-cloud-functions.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'backend/**'
      - 'functions/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging
          - development
      skip_tests:
        description: 'Skip tests'
        required: false
        default: false
        type: boolean

env:
  NODE_VERSION: '18'
  YC_FOLDER_ID: ${{ secrets.YC_FOLDER_ID }}
  YC_SERVICE_ACCOUNT_ID: ${{ secrets.YC_SERVICE_ACCOUNT_ID }}
  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
  API_KEY: ${{ secrets.API_KEY }}
  REQUIRED_CHANNELS: ${{ secrets.REQUIRED_CHANNELS }}

jobs:
  # Проверка и тестирование кода
  test:
    name: 🧪 Test Code
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || (github.event_name == 'workflow_dispatch' && !inputs.skip_tests)
    
    steps:
    - name: 🔄 Checkout code
      uses: actions/checkout@v4
      
    - name: 🔧 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: functions/package-lock.json
        
    - name: 📦 Install dependencies
      run: |
        cd functions
        npm ci
        
    - name: 🔍 Lint code
      run: |
        cd functions
        npm run lint || echo "Linting warnings found"
        
    - name: 🧪 Run tests
      run: |
        cd functions
        npm test || echo "No tests configured"
        
    - name: 📊 Code analysis
      run: |
        echo "## 📊 Code Analysis Results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "| File | Size | Status |" >> $GITHUB_STEP_SUMMARY
        echo "|------|------|--------|" >> $GITHUB_STEP_SUMMARY
        
        cd functions
        for file in *.js; do
          size=$(wc -c < "$file")
          if [ $size -gt 10000 ]; then
            status="⚠️ Large"
          else
            status="✅ OK"
          fi
          echo "| $file | ${size} bytes | $status |" >> $GITHUB_STEP_SUMMARY
        done

  # Развертывание на Yandex Cloud Functions
  deploy:
    name: 🚀 Deploy to Yandex Cloud Functions
    runs-on: ubuntu-latest
    needs: [test]
    if: always() && (needs.test.result == 'success' || needs.test.result == 'skipped') && github.ref == 'refs/heads/main'
    environment: 
      name: ${{ github.event.inputs.environment || 'production' }}
      url: ${{ steps.deploy.outputs.gateway_url }}
    
    outputs:
      gateway_url: ${{ steps.deploy.outputs.gateway_url }}
      api_function_id: ${{ steps.deploy.outputs.api_function_id }}
      webhook_function_id: ${{ steps.deploy.outputs.webhook_function_id }}
    
    steps:
    - name: 🔄 Checkout code
      uses: actions/checkout@v4
      
    - name: 🔧 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: functions/package-lock.json
        
    - name: 🔧 Setup Yandex Cloud CLI
      uses: yc-actions/yc-cli-install@v1
      with:
        yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
        
    - name: 📦 Install production dependencies
      run: |
        cd functions
        npm ci --only=production --silent
        
        # Очищаем кэш npm для уменьшения размера
        npm cache clean --force
        
        # Удаляем dev зависимости если они есть
        rm -rf node_modules/.cache
        
    - name: 🗜️ Create deployment package
      run: |
        cd functions
        
        # Создаем архив с исключением ненужных файлов
        zip -r ../functions.zip . \
          -x "node_modules/.cache/*" \
             "*.log" \
             "test/*" \
             "*.test.js" \
             "*.spec.js" \
             ".git/*" \
             "README.md"
        
        # Проверяем размер архива
        ARCHIVE_SIZE=$(stat -c%s "../functions.zip")
        ARCHIVE_SIZE_MB=$((ARCHIVE_SIZE / 1024 / 1024))
        
        echo "📦 Archive size: ${ARCHIVE_SIZE_MB} MB"
        
        if [ $ARCHIVE_SIZE_MB -gt 128 ]; then
          echo "⚠️ Warning: Archive size exceeds 128 MB limit"
          exit 1
        fi
        
        echo "archive_size=${ARCHIVE_SIZE_MB}" >> $GITHUB_OUTPUT
        
    - name: 🚀 Deploy API Function
      id: deploy_api
      run: |
        echo "🚀 Deploying API Function..."
        
        # Проверяем существование функции
        if yc serverless function get hsk-api-function >/dev/null 2>&1; then
          echo "📝 Function exists, creating new version"
        else
          echo "🆕 Creating new function"
          yc serverless function create \
            --name hsk-api-function \
            --description "HSK Telegram Bot API endpoints"
        fi
        
        # Создаем новую версию функции
        yc serverless function version create \
          --function-name hsk-api-function \
          --runtime nodejs18 \
          --entrypoint api-handler.handler \
          --memory 256m \
          --execution-timeout 30s \
          --source-path functions.zip \
          --environment NODE_ENV=${{ github.event.inputs.environment || 'production' }},TELEGRAM_BOT_TOKEN=${{ env.TELEGRAM_BOT_TOKEN }},API_KEY=${{ env.API_KEY }},REQUIRED_CHANNELS="${{ env.REQUIRED_CHANNELS }}"
        
        # Получаем ID функции
        API_FUNCTION_ID=$(yc serverless function get hsk-api-function --format json | jq -r '.id')
        echo "api_function_id=${API_FUNCTION_ID}" >> $GITHUB_OUTPUT
        echo "✅ API Function deployed: ${API_FUNCTION_ID}"
        
    - name: 🚀 Deploy Telegram Webhook Function
      id: deploy_webhook
      run: |
        echo "🚀 Deploying Telegram Webhook Function..."
        
        # Проверяем существование функции
        if yc serverless function get hsk-telegram-webhook >/dev/null 2>&1; then
          echo "📝 Function exists, creating new version"
        else
          echo "🆕 Creating new function"
          yc serverless function create \
            --name hsk-telegram-webhook \
            --description "HSK Telegram Bot webhook handler"
        fi
        
        # Создаем новую версию функции
        yc serverless function version create \
          --function-name hsk-telegram-webhook \
          --runtime nodejs18 \
          --entrypoint telegram-webhook.handler \
          --memory 128m \
          --execution-timeout 15s \
          --source-path functions.zip \
          --environment NODE_ENV=${{ github.event.inputs.environment || 'production' }},TELEGRAM_BOT_TOKEN=${{ env.TELEGRAM_BOT_TOKEN }}
        
        # Получаем ID функции
        WEBHOOK_FUNCTION_ID=$(yc serverless function get hsk-telegram-webhook --format json | jq -r '.id')
        echo "webhook_function_id=${WEBHOOK_FUNCTION_ID}" >> $GITHUB_OUTPUT
        echo "✅ Webhook Function deployed: ${WEBHOOK_FUNCTION_ID}"
        
    - name: 🌐 Deploy API Gateway
      id: deploy_gateway
      run: |
        echo "🌐 Deploying API Gateway..."
        
        # Получаем ID функций
        API_FUNCTION_ID="${{ steps.deploy_api.outputs.api_function_id }}"
        WEBHOOK_FUNCTION_ID="${{ steps.deploy_webhook.outputs.webhook_function_id }}"
        
        # Обновляем спецификацию API Gateway
        sed "s/<API_FUNCTION_ID>/${API_FUNCTION_ID}/g" api-gateway-spec.yaml > api-gateway-spec-temp.yaml
        sed -i "s/<TELEGRAM_WEBHOOK_FUNCTION_ID>/${WEBHOOK_FUNCTION_ID}/g" api-gateway-spec-temp.yaml
        sed -i "s/<SERVICE_ACCOUNT_ID>/${{ env.YC_SERVICE_ACCOUNT_ID }}/g" api-gateway-spec-temp.yaml
        
        # Проверяем существование API Gateway
        if yc serverless api-gateway get hsk-api-gateway >/dev/null 2>&1; then
          echo "📝 API Gateway exists, updating"
          yc serverless api-gateway update hsk-api-gateway \
            --spec api-gateway-spec-temp.yaml
        else
          echo "🆕 Creating new API Gateway"
          yc serverless api-gateway create \
            --name hsk-api-gateway \
            --description "HSK Telegram Bot API Gateway" \
            --spec api-gateway-spec-temp.yaml
        fi
        
        # Получаем URL API Gateway
        GATEWAY_DOMAIN=$(yc serverless api-gateway get hsk-api-gateway --format json | jq -r '.domain')
        GATEWAY_URL="https://${GATEWAY_DOMAIN}"
        
        echo "gateway_url=${GATEWAY_URL}" >> $GITHUB_OUTPUT
        echo "✅ API Gateway deployed: ${GATEWAY_URL}"
        
    - name: 🔗 Setup Telegram Webhook
      run: |
        echo "🔗 Setting up Telegram webhook..."
        
        GATEWAY_URL="${{ steps.deploy_gateway.outputs.gateway_url }}"
        WEBHOOK_URL="${GATEWAY_URL}/webhook/telegram"
        
        # Устанавливаем webhook
        RESPONSE=$(curl -s -X POST "https://api.telegram.org/bot${{ env.TELEGRAM_BOT_TOKEN }}/setWebhook" \
          -H "Content-Type: application/json" \
          -d "{
            \"url\": \"${WEBHOOK_URL}\",
            \"allowed_updates\": [\"message\", \"callback_query\"]
          }")
        
        # Проверяем результат
        if echo "$RESPONSE" | jq -r '.ok' | grep -q true; then
          echo "✅ Telegram webhook set: ${WEBHOOK_URL}"
        else
          echo "❌ Failed to set Telegram webhook"
          echo "Response: $RESPONSE"
          exit 1
        fi
        
    - name: 🔍 Test deployment
      id: test_deployment
      run: |
        echo "🔍 Testing deployment..."
        
        GATEWAY_URL="${{ steps.deploy_gateway.outputs.gateway_url }}"
        
        # Тест health endpoint
        echo "Testing health endpoint..."
        HEALTH_RESPONSE=$(curl -s -f "${GATEWAY_URL}/health" || echo "failed")
        
        if echo "$HEALTH_RESPONSE" | jq -r '.status' | grep -q ok; then
          echo "✅ Health check: PASSED"
          echo "health_status=passed" >> $GITHUB_OUTPUT
        else
          echo "❌ Health check: FAILED"
          echo "Response: $HEALTH_RESPONSE"
          echo "health_status=failed" >> $GITHUB_OUTPUT
        fi
        
        # Тест API endpoint
        echo "Testing API endpoint..."
        API_RESPONSE=$(curl -s -f -H "x-api-key: ${{ env.API_KEY }}" "${GATEWAY_URL}/api/subscription/channels" || echo "failed")
        
        if echo "$API_RESPONSE" | jq -r '.success' | grep -q true; then
          CHANNELS_COUNT=$(echo "$API_RESPONSE" | jq -r '.total')
          echo "✅ API test: PASSED (${CHANNELS_COUNT} channels found)"
          echo "api_status=passed" >> $GITHUB_OUTPUT
        else
          echo "⚠️ API test: WARNING"
          echo "Response: $API_RESPONSE"
          echo "api_status=warning" >> $GITHUB_OUTPUT
        fi
        
    - name: 📊 Deployment summary
      run: |
        GATEWAY_URL="${{ steps.deploy_gateway.outputs.gateway_url }}"
        
        echo "## 🎉 Cloud Functions Deployment Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### 📋 Deployment Details" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "| Parameter | Value |" >> $GITHUB_STEP_SUMMARY
        echo "|-----------|-------|" >> $GITHUB_STEP_SUMMARY
        echo "| Environment | ${{ github.event.inputs.environment || 'production' }} |" >> $GITHUB_STEP_SUMMARY
        echo "| Node.js Version | ${{ env.NODE_VERSION }} |" >> $GITHUB_STEP_SUMMARY
        echo "| Archive Size | ${{ steps.create_package.outputs.archive_size }} MB |" >> $GITHUB_STEP_SUMMARY
        echo "| API Function ID | ${{ steps.deploy_api.outputs.api_function_id }} |" >> $GITHUB_STEP_SUMMARY
        echo "| Webhook Function ID | ${{ steps.deploy_webhook.outputs.webhook_function_id }} |" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### 🔗 Endpoints" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "| Endpoint | URL | Status |" >> $GITHUB_STEP_SUMMARY
        echo "|----------|-----|--------|" >> $GITHUB_STEP_SUMMARY
        echo "| API Gateway | ${GATEWAY_URL} | ✅ Active |" >> $GITHUB_STEP_SUMMARY
        echo "| Health Check | ${GATEWAY_URL}/health | ${{ steps.test_deployment.outputs.health_status == 'passed' && '✅ Passed' || '❌ Failed' }} |" >> $GITHUB_STEP_SUMMARY
        echo "| API Endpoint | ${GATEWAY_URL}/api/subscription/channels | ${{ steps.test_deployment.outputs.api_status == 'passed' && '✅ Passed' || steps.test_deployment.outputs.api_status == 'warning' && '⚠️ Warning' || '❌ Failed' }} |" >> $GITHUB_STEP_SUMMARY
        echo "| Telegram Webhook | ${GATEWAY_URL}/webhook/telegram | ✅ Configured |" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### 📝 Next Steps" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "1. Test the Telegram bot by sending /start command" >> $GITHUB_STEP_SUMMARY
        echo "2. Monitor function logs in Yandex Cloud Console" >> $GITHUB_STEP_SUMMARY
        echo "3. Check API Gateway metrics" >> $GITHUB_STEP_SUMMARY
        echo "4. Update frontend BACKEND_URL to: ${GATEWAY_URL}" >> $GITHUB_STEP_SUMMARY
        
    - name: 🧹 Cleanup
      if: always()
      run: |
        echo "🧹 Cleaning up temporary files..."
        rm -f functions.zip
        rm -f api-gateway-spec-temp.yaml
        echo "✅ Cleanup completed"

  # Мониторинг после развертывания
  monitor:
    name: 📊 Post-deployment Monitoring
    runs-on: ubuntu-latest
    needs: [deploy]
    if: success() && github.ref == 'refs/heads/main'
    
    steps:
    - name: 🔧 Setup Yandex Cloud CLI
      uses: yc-actions/yc-cli-install@v1
      with:
        yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
        
    - name: 📊 Check function metrics
      run: |
        echo "📊 Checking function metrics..."
        
        # Получаем статистику функций
        echo "## 📊 Function Statistics" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        for func_name in "hsk-api-function" "hsk-telegram-webhook"; do
          echo "### ${func_name}" >> $GITHUB_STEP_SUMMARY
          
          # Получаем информацию о функции
          FUNC_INFO=$(yc serverless function get $func_name --format json)
          
          MEMORY=$(echo "$FUNC_INFO" | jq -r '.resources.memory')
          TIMEOUT=$(echo "$FUNC_INFO" | jq -r '.timeout')
          RUNTIME=$(echo "$FUNC_INFO" | jq -r '.runtime')
          
          echo "- Memory: ${MEMORY}" >> $GITHUB_STEP_SUMMARY
          echo "- Timeout: ${TIMEOUT}" >> $GITHUB_STEP_SUMMARY
          echo "- Runtime: ${RUNTIME}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
        done
        
    - name: 📋 Get recent logs
      run: |
        echo "📋 Getting recent function logs..."
        
        for func_name in "hsk-api-function" "hsk-telegram-webhook"; do
          echo "\n=== Logs for ${func_name} ==="
          
          FUNC_ID=$(yc serverless function get $func_name --format json | jq -r '.id')
          
          # Получаем логи за последние 10 минут
          yc logging read \
            --group-name default \
            --resource-type serverless.function \
            --resource-id $FUNC_ID \
            --since 10m \
            --limit 20 || echo "No recent logs found"
        done

  # Уведомление об успешном развертывании
  notify:
    name: 📢 Notify Success
    runs-on: ubuntu-latest
    needs: [deploy, monitor]
    if: success() && github.ref == 'refs/heads/main'
    
    steps:
    - name: 📢 Success notification
      run: |
        echo "🎉 HSK Telegram Bot successfully deployed to Yandex Cloud Functions!"
        echo "Gateway URL: ${{ needs.deploy.outputs.gateway_url }}"
        echo "Environment: ${{ github.event.inputs.environment || 'production' }}"
        echo "Commit: ${{ github.sha }}"
        
        # Здесь можно добавить отправку уведомлений в Slack, Discord, etc.
        # Например:
        # curl -X POST -H 'Content-type: application/json' \
        #   --data '{"text":"🎉 HSK Bot deployed successfully!"}' \
        #   ${{ secrets.SLACK_WEBHOOK_URL }}