name: Deploy to Yandex Cloud

on:
  push:
    branches: [ main, master ]
    paths: 
      - 'backend/**'
      - '.github/workflows/deploy-yandex-cloud.yml'
  workflow_dispatch:
    inputs:
      force_deploy:
        description: 'Force deployment'
        required: false
        default: 'false'

env:
  REGISTRY_ID: ${{ secrets.YC_REGISTRY_ID }}
  VM_NAME: hsk-backend
  IMAGE_TAG: cr.yandex/${{ secrets.YC_REGISTRY_ID }}/hsk-backend

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 🔄 Checkout code
      uses: actions/checkout@v4
      
    - name: 🔧 Setup Yandex Cloud CLI
      uses: yc-actions/yc-cli-install@v2
      with:
        yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
        
    - name: 🐳 Login to Container Registry
      run: yc container registry configure-docker
      
    - name: 🏷️ Generate image tag
      id: image_tag
      run: |
        echo "IMAGE_TAG_FULL=${IMAGE_TAG}:${GITHUB_SHA::8}" >> $GITHUB_OUTPUT
        echo "IMAGE_TAG_LATEST=${IMAGE_TAG}:latest" >> $GITHUB_OUTPUT
        
    - name: 🔨 Build Docker image
      run: |
        cd backend
        docker build \
          --tag ${{ steps.image_tag.outputs.IMAGE_TAG_FULL }} \
          --tag ${{ steps.image_tag.outputs.IMAGE_TAG_LATEST }} \
          --build-arg NODE_ENV=production \
          .
          
    - name: 🧪 Test Docker image
      run: |
        # Запускаем контейнер для тестирования
        docker run -d \
          --name test-container \
          -p 3000:8080 \
          -e NODE_ENV=production \
          -e PORT=8080 \
          -e API_KEY=test_key \
          ${{ steps.image_tag.outputs.IMAGE_TAG_FULL }}
        
        # Ждем запуска
        sleep 10
        
        # Проверяем health endpoint
        if curl -f http://localhost:3000/health; then
          echo "✅ Health check passed"
        else
          echo "❌ Health check failed"
          docker logs test-container
          exit 1
        fi
        
        # Останавливаем тестовый контейнер
        docker stop test-container
        docker rm test-container
        
    - name: 📤 Push to Container Registry
      run: |
        docker push ${{ steps.image_tag.outputs.IMAGE_TAG_FULL }}
        docker push ${{ steps.image_tag.outputs.IMAGE_TAG_LATEST }}
        
    - name: 🔍 Check if VM exists
      id: vm_check
      run: |
        if yc compute instance get $VM_NAME >/dev/null 2>&1; then
          echo "VM_EXISTS=true" >> $GITHUB_OUTPUT
          echo "ℹ️ VM $VM_NAME already exists"
        else
          echo "VM_EXISTS=false" >> $GITHUB_OUTPUT
          echo "ℹ️ VM $VM_NAME does not exist"
        fi
        
    - name: 🔄 Update existing VM
      if: steps.vm_check.outputs.VM_EXISTS == 'true'
      run: |
        echo "🔄 Updating existing VM..."
        yc compute instance update-container $VM_NAME \
          --container-image ${{ steps.image_tag.outputs.IMAGE_TAG_LATEST }} \
          --container-env NODE_ENV=production,PORT=8080,TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }},FRONTEND_URL=${{ secrets.FRONTEND_URL }},API_KEY=${{ secrets.API_KEY }},REQUIRED_CHANNELS=${{ secrets.REQUIRED_CHANNELS }} \
          --container-restart-policy always
          
    - name: 🚀 Create new VM
      if: steps.vm_check.outputs.VM_EXISTS == 'false'
      run: |
        echo "🚀 Creating new VM..."
        yc compute instance create \
          --name $VM_NAME \
          --zone ru-central1-a \
          --network-interface subnet-name=default-ru-central1-a,nat-ip-version=ipv4 \
          --create-boot-disk image-folder-id=standard-images,image-family=container-optimized-image,size=20GB \
          --cores 2 \
          --memory 2GB \
          --container-name hsk-app \
          --container-image ${{ steps.image_tag.outputs.IMAGE_TAG_LATEST }} \
          --container-env NODE_ENV=production,PORT=8080,TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }},FRONTEND_URL=${{ secrets.FRONTEND_URL }},API_KEY=${{ secrets.API_KEY }},REQUIRED_CHANNELS=${{ secrets.REQUIRED_CHANNELS }} \
          --container-restart-policy always \
          --labels project=hsk,environment=production
          
    - name: 🌐 Get VM IP address
      id: vm_ip
      run: |
        VM_IP=$(yc compute instance get $VM_NAME --format json | jq -r '.network_interfaces[0].primary_v4_address.one_to_one_nat.address')
        echo "VM_IP=$VM_IP" >> $GITHUB_OUTPUT
        echo "🌐 VM IP address: $VM_IP"
        
    - name: ⏳ Wait for application startup
      run: |
        echo "⏳ Waiting for application to start..."
        sleep 60
        
    - name: 🔍 Health check
      run: |
        VM_IP=${{ steps.vm_ip.outputs.VM_IP }}
        HEALTH_URL="http://$VM_IP:8080/health"
        
        echo "🔍 Checking application health at $HEALTH_URL"
        
        # Попытки проверки здоровья с повторами
        for i in {1..5}; do
          if curl -f --connect-timeout 10 --max-time 30 "$HEALTH_URL"; then
            echo "✅ Health check passed on attempt $i"
            break
          else
            echo "⚠️ Health check failed on attempt $i"
            if [ $i -eq 5 ]; then
              echo "❌ All health check attempts failed"
              echo "📋 VM logs:"
              yc compute instance get-serial-port-output $VM_NAME --lines 50
              exit 1
            fi
            sleep 15
          fi
        done
        
    - name: 🧪 API endpoint test
      run: |
        VM_IP=${{ steps.vm_ip.outputs.VM_IP }}
        API_URL="http://$VM_IP:8080/api/subscription/channels"
        
        echo "🧪 Testing API endpoint: $API_URL"
        
        # Тестируем API endpoint
        HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
          -H "x-api-key: ${{ secrets.API_KEY }}" \
          --connect-timeout 10 \
          --max-time 30 \
          "$API_URL")
          
        if [ "$HTTP_STATUS" -eq 200 ]; then
          echo "✅ API endpoint test passed (HTTP $HTTP_STATUS)"
        else
          echo "⚠️ API endpoint returned HTTP $HTTP_STATUS"
          # Не прерываем деплой, так как это может быть связано с настройками Telegram
        fi
        
    - name: 📊 Deployment summary
      run: |
        VM_IP=${{ steps.vm_ip.outputs.VM_IP }}
        
        echo "## 🎉 Deployment Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "| Parameter | Value |" >> $GITHUB_STEP_SUMMARY
        echo "|-----------|-------|" >> $GITHUB_STEP_SUMMARY
        echo "| VM Name | $VM_NAME |" >> $GITHUB_STEP_SUMMARY
        echo "| VM IP | $VM_IP |" >> $GITHUB_STEP_SUMMARY
        echo "| Image | ${{ steps.image_tag.outputs.IMAGE_TAG_LATEST }} |" >> $GITHUB_STEP_SUMMARY
        echo "| Commit | ${{ github.sha }} |" >> $GITHUB_STEP_SUMMARY
        echo "| Branch | ${{ github.ref_name }} |" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### 🔗 Useful Links" >> $GITHUB_STEP_SUMMARY
        echo "- **API Health Check**: http://$VM_IP:8080/health" >> $GITHUB_STEP_SUMMARY
        echo "- **API Endpoint**: http://$VM_IP:8080/api/subscription/channels" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### 📝 Next Steps" >> $GITHUB_STEP_SUMMARY
        echo "1. Update frontend configuration with new API URL" >> $GITHUB_STEP_SUMMARY
        echo "2. Update Telegram bot webhook URL" >> $GITHUB_STEP_SUMMARY
        echo "3. Test all application features" >> $GITHUB_STEP_SUMMARY
        
    - name: 💬 Notify on failure
      if: failure()
      run: |
        echo "❌ Deployment failed!"
        echo "📋 Recent VM logs:"
        yc compute instance get-serial-port-output $VM_NAME --lines 100 || echo "Could not retrieve logs"
        
  cleanup:
    runs-on: ubuntu-latest
    needs: deploy
    if: always()
    
    steps:
    - name: 🧹 Cleanup old images
      uses: yc-actions/yc-cli-install@v2
      with:
        yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
        
    - name: 🗑️ Remove old container images
      run: |
        echo "🗑️ Cleaning up old images..."
        
        # Получаем список всех образов
        IMAGES=$(yc container image list --repository-name cr.yandex/${{ secrets.YC_REGISTRY_ID }}/hsk-backend --format json)
        
        # Оставляем только последние 5 образов
        echo "$IMAGES" | jq -r 'sort_by(.created_at) | reverse | .[5:] | .[].id' | while read -r IMAGE_ID; do
          if [ -n "$IMAGE_ID" ]; then
            echo "Deleting image: $IMAGE_ID"
            yc container image delete "$IMAGE_ID" || echo "Failed to delete $IMAGE_ID"
          fi
        done
        
        echo "✅ Cleanup completed"